project:
  type: website
  output-dir: docs

website:
  title: "Data Geoviz"
  navbar:
    background: "#FFFFFF"
    foreground: "dark"
    right:
      - href: index.qmd
        text: "Home"
      - href: posts.qmd  
        text: "Post"
      - text: "Project"
        href: blog.qmd
      - icon: github
        href: https://github.com/datageoviz

format:
  html:
    theme: ember.scss
    css: styles.css
    toc: true
    linkcolor: blue

editor: visual

