project:
  type: website
  output-dir: docs

website:
  title: "Data Geoviz"
  navbar:
    background: "#FFFFFF"
    foreground: "dark"
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - posts.qmd
      - text: "Blog"
        href: blog.qmd

format:
  html:
    theme: ember.scss
    css: styles.css
    toc: true
    linkcolor: black

editor: visual

